version: "3.8"

services:

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - .:/app 

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    tty: true
    stdin_open: true
    command: bash -c "ollama pull mistral && ollama serve"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu] 

volumes:
  ollama_data:
